---
- hosts: localhost
version: 1.0
run-as: root
env:
  variables:
      ENV_NAME: "DEV"
phases:
  install:
    commands:
      - "apt update"
  pre_build:
    commands:
       - npm install
  build:
    commands:
       - npm run build --if-present
       - ls -lart
       - npm run test
  post_build:
    commands:
       - "npm run test:e2e"
artifacts:
  files:
     - "**/*"
  name: artifact
cache:
  paths:
     - "node_modules/**/*"
