---
- hosts: webservers
  tasks:
   - name: Install forever
     npm: name=forever global=yes state=present
   - name: Go to the folder and execute command
     command: chdir=/home/ubuntu/SonarQubeNodeJS npm install
   - name: start App
     command: forever start /home/ubuntu/SonarQubeNodeJS/app/server.js
    
